#debug: true
      
spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:~/todo
    username: sa
    password: 
  jpa:
    database: h2
    show-sql: true
    hibernate:
      ddl-auto: create